//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.Sales = new HashSet<Sales>();
        }
    
        public int Id { get; set; }
        public int VendorId { get; set; }
        public string Name { get; set; }
        public int MeasureId { get; set; }
        public decimal BasePrice { get; set; }
    
        public virtual Measurements Measurements { get; set; }
        public virtual Vendors Vendors { get; set; }
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
