//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int SaleId { get; set; }
        public int ProductId { get; set; }
        public int DateId { get; set; }
        public double Quantity { get; set; }
        public int SupermarketId { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Sum { get; set; }
    
        public virtual Dates Dates { get; set; }
        public virtual Products Products { get; set; }
        public virtual Supermarkets Supermarkets { get; set; }
    }
}
